version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      site-dependencies:
        patterns: ['*']

  - package-ecosystem: npm
    directory: /workers/api
    schedule:
      interval: weekly
    groups:
      worker-dependencies:
        patterns: ['*']

  - package-ecosystem: pip
    directory: /agent
    schedule:
      interval: weekly
    groups:
      agent-dependencies:
        patterns: ['*']

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
